### ISSUE TITLE
.exe size

### ISSUE THREAD

**Issue by keith-gardner** [BrantaOps/branta-windows#189]
Our .exe is 190 MB, can we slim it?

Try Removing:
- https://github.com/BrantaOps/branta-windows/blob/main/Branta/Assets/goldblackcropped.jpg
- https://github.com/BrantaOps/branta-windows/blob/main/Branta/Assets/goldwhitecropped.png

**Comment by kylemccullen** [comment]
MSI size is large because a copy of .NET is included in the exe. This is necessary for the application to run without the user having to install a version of .NET

There are some potential options to reduce binary size
 * Feature Trimming https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-8-0#trimming-framework-library-features
 * AOT compilation https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net8plus%2Cwindows#limitations-of-native-aot-deployment

**Comment by keith-gardner** [comment]
Okay - .msi in [0.0.5](https://github.com/BrantaOps/branta-windows/releases/tag/0.0.5) is 64MB. 

Lets close this unless we require having an exe for anything.
